Support for sub-paths
lldap/lldap pull request #752
Opened 2023-12-05 15:49 UTC by MinerSebas

This adds support for placing lldap on a sub-path.

To use it, a User needs to set the `http_url` setting to a URL with a sub-path (`http://example.com/lldap`) and setup the reverse-proxy to strip the sub-path.
Caddy example:
```
handle_path /lldap* {
  reverse_proxy http://127.0.0.1:17170
}
```

Future Work:
Currently, the sub-path is injected every time `index.html` and `main.js` are called, but this could be cached instead.
I tried it, but I never used actix before, and thus couldn't make it work.

2023-12-05 16:19 UTC, nitnelave requested changes
Looks nice!

Can you make sure the email reset works with the subpath?
Also, make sure to try in a private window to clear the caches, in case.

2023-12-05 16:19 UTC, nitnelave commented on server/src/infra/tcp_server.rs
> +            .split_terminator("<base href=\"/\">")
I think you can use https://doc.rust-lang.org/std/string/struct.String.html#method.replace instead.

2023-12-05 16:19 UTC, nitnelave commented on server/src/infra/tcp_server.rs
> +            .split_terminator("/pkg/")
Same here

2023-12-05 16:19 UTC, nitnelave commented on app/src/infra/api.rs
> +    yew_router::utils::base_url().unwrap_or_default()
This reads from the `<base>` tag?

2023-12-05 18:11 UTC, MinerSebas commented on app/src/infra/api.rs
> +    yew_router::utils::base_url().unwrap_or_default()
Yes, that's what it does.

2023-12-05 18:22 UTC, MinerSebas commented
> Can you make sure the email reset works with the subpath?

Confirmed on Discord that email resetting works correctly.

> Also, make sure to try in a private window to clear the caches, in case.

Everything works correctly.

2023-12-05 20:05 UTC, nitnelave commented on server/src/infra/auth_service.rs
> +    if path != "/" {
If the URL ends with a slash, is it trimmed when calling path()? Or could you end up with 2 slashes here?

It seems more straightforward to say `if !path.ends_with("/")`

2023-12-07 09:08 UTC, nitnelave approved these changes

2023-12-07 17:21 UTC, merged

2023-12-07 17:22 UTC, nitnelave commented
Thank you for the contribution!