Add pre packaged repo
lldap/lldap pull request #768
Opened 2023-12-18 10:04 UTC by martadinata666

This dissussion #765 shown different behaviour than it expected. Add more description to it.

2023-12-18 10:10 UTC, nitnelave requested changes

2023-12-18 10:10 UTC, nitnelave commented on README.md
> +The pre-packaged per distribution can be fetched [LLDAP OBS](https://software.opensuse.org//download.html?project=home%3AMasgalor%3ALLDAP&package=lldap)
Small nits on the formulation:

The package for these distributions can be found at LLDAP OBS (link).
When using the distributed package, the default login is `admin`/`password`. You can change that from the web UI after starting the service.

2023-12-19 09:58 UTC, nitnelave commented
I'm not sure I understand the formatting updates. Why the changes?

2023-12-19 11:58 UTC, martadinata666 commented
The README.md gets more cluttered every time information is added. Formatting changes just to better readability/look at pieces of information. We can revert in, of course.

2023-12-19 12:33 UTC, nitnelave approved these changes

2023-12-19 12:34 UTC, merged